In [95]:
import numpy as np  
np.random.seed(0)
x = np.random.randint(10, size=(3, 4))
print(x)


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [96]:
np.less(x, 5)

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [118]:
from regex import F


np.equal(x, 3)
print(np.sum(np.equal(x, 3) == False))

9


In [98]:


a = x[x>3]
#sum of elements greater than 3
print(np.sum(a))

43


In [99]:
o = x[x%2!=0]
print(o)
print(np.prod(o))
print(5*3*3*7*9*3*5*7)

[5 3 3 7 9 3 5 7]
297675
297675


In [102]:
# nhap1.ipynb
import numpy as np
from prime_number import is_prime

# Define the array x
np.random.seed(0)
x = np.random.randint(10, size=(3, 4))
# Filter prime numbers using the is_prime function
prime_numbers = list(filter(is_prime, x.flatten()))

# Print the prime numbers
print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [5, 3, 3, 7, 3, 5, 2, 7]


In [103]:
pp = [1,2,3,4,5]
print( list(filter(lambda x: x%2==0, pp)))

[2, 4]


In [107]:


vectorized_is_prime = np.vectorize(is_prime)
prime_numbers = vectorized_is_prime(x)
print(prime_numbers)
print(np.sum(x[prime_numbers]))

[[ True False  True  True]
 [ True False  True  True]
 [ True False  True False]]
35


In [110]:
np.sort(x, axis=0)


array([[2, 0, 3, 3],
       [5, 4, 3, 5],
       [7, 9, 7, 6]])

In [ ]:
np.sort(x, axis=1, )

array([[0, 3, 3, 5],
       [3, 5, 7, 9],
       [2, 4, 6, 7]])

In [114]:
np.sort(x, axis=None)

array([0, 2, 3, 3, 3, 4, 5, 5, 6, 7, 7, 9])